// <auto-generated />
using Day02Exercises.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day02Exercises.Migrations
{
    [DbContext(typeof(ProduceDBContext))]
    partial class ProduceDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Day02Exercises.Models.Produce", b =>
                {
                    b.Property<int>("ProduceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduceID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProduceID");

                    b.ToTable("Produces");

                    b.HasData(
                        new
                        {
                            ProduceID = 1,
                            Description = "Oranges"
                        },
                        new
                        {
                            ProduceID = 2,
                            Description = "Apples"
                        },
                        new
                        {
                            ProduceID = 3,
                            Description = "Peaches"
                        });
                });

            modelBuilder.Entity("Day02Exercises.Models.ProduceSupplier", b =>
                {
                    b.Property<int>("ProduceID")
                        .HasColumnType("int");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("ProduceID", "SupplierID");

                    b.HasIndex("SupplierID");

                    b.ToTable("ProduceSuppliers");

                    b.HasData(
                        new
                        {
                            ProduceID = 1,
                            SupplierID = 1,
                            Qty = 25
                        },
                        new
                        {
                            ProduceID = 2,
                            SupplierID = 2,
                            Qty = 12
                        },
                        new
                        {
                            ProduceID = 3,
                            SupplierID = 1,
                            Qty = 30
                        });
                });

            modelBuilder.Entity("Day02Exercises.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"), 1L, 1);

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierID = 1,
                            SupplierName = "Kin's Market"
                        },
                        new
                        {
                            SupplierID = 2,
                            SupplierName = "Fresh Street Market"
                        });
                });

            modelBuilder.Entity("Day02Exercises.Models.ProduceSupplier", b =>
                {
                    b.HasOne("Day02Exercises.Models.Produce", "Produce")
                        .WithMany("ProduceSuppliers")
                        .HasForeignKey("ProduceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Day02Exercises.Models.Supplier", "Supplier")
                        .WithMany("ProduceSuppliers")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produce");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Day02Exercises.Models.Produce", b =>
                {
                    b.Navigation("ProduceSuppliers");
                });

            modelBuilder.Entity("Day02Exercises.Models.Supplier", b =>
                {
                    b.Navigation("ProduceSuppliers");
                });
#pragma warning restore 612, 618
        }
    }
}
